name: podgoroy-site

services:
  podgoroy-remaster-app:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: podgoroy-remaster:latest
    container_name: podgoroy-remaster-app
    restart: unless-stopped
    env_file:
      - ../../.env.production
    environment:
      DIRECTUS_INTERNAL_URL: ${DIRECTUS_INTERNAL_URL:-http://podgoroy-cms-app:8055}
    ports:
      - "127.0.0.1:3011:3000"
    networks:
      - default
      - cms

networks:
  default:
  cms:
    external: true
    name: podgoroy-cms_default
